### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by jeichert** [carrot/roots-contentful#10]
Just curious if there is a way to make use of contentful's api to resize images on delivery, I'd like to be able to query thumbnails on the index page, as well as the full size images on the individual post pages. Not sure if there is a configuration setting in app.coffee that can be used, but could be an interesting feature to add in the future, if possible.

**Comment by joshrowley** [comment]
Hey @jeichert, glad to see you're interested in the project here, just curious, how have you been using roots-contentful, are you using it in production at all?

It looks like you are able to [resize images](https://www.contentful.com/developers/documentation/content-delivery-api/javascript/#image-asset-resizing) during delivery by adding a query string to the image URL that Contentful's API feeds you. So probably the best way to include this in contentful would be an view helper that roots-contentful would provide:

```jade
- for post in contentful.blog_posts
  h1= post.title
  img(src= asset(post.image, w: 100, h: 100, q: 50, fm: 'png'))
```

What do you think?

**Comment by jeichert** [comment]
Hey sorry about the major delay on the response.  I'm not using roots/roots-contentful in production yet, I've been teaching myself javascript / coffeescript as of late, as a foray into programming. Only other experience is some custom theming for wordpress. But I've been reading a number of posts on static site generators, and after a bit of fiddling with a number of them, roots came out as my favorite.  

The query string/helper that you've shown seems incredibly useful.  Something I'd definitely be interested in, and would use all the time (I've got a couple of projects I can see using roots/roots-contenful for in the coming future).

**Comment by joshrowley** [comment]
@jeichert Cool! Well we're super happy to hear that you chose roots. Especially if you've recently gotten started with programming, please let us know if there are any confusing bits in the docs or with getting set up, we definitely want roots to be an approachable project for all levels of experience.

I'll definitely take a look at adding this helper into roots-contentful some time this weekend.

Let us know when you build something with it and you can [PR](https://github.com/carrot/roots-www) into the [roots site](http://roots.cx/articles/built-with-roots).

**Comment by jeichert** [comment]
Awesome, definitely will do, so far so good with both roots and roots-contentful, between the docs and the screencasts on the website I've been moving along fairly easily.  Will definitely do a PR when I get the site up and running fully. 

Thanks!

**Comment by joshrowley** [comment]
Sweet, I'm gonna keep this open as a note to myself to get to this.
