### ISSUE TITLE
render markdown issues

### ISSUE THREAD

**Issue by javaporter** [carrot/roots-contentful#13]
Per the readme, I would assume `= markdown(post.body)` would spit out my content as markdown. However, this just produces an error (undefined is not a function). If I just do `= post.body`, all the markdown is parsed out of it.

I can tell that I'm getting the original markdown due to your handy suggested `= JSON.stringify(post.body)`, but am not sure how to translate this into something more legible. Am I missing a dependency in my package maybe?

**Comment by kylemac** [comment]
@javaporter to have access to a `markdown` function, you need to ensure it's being passed to your view as a local. this can be done in your `app.coffee` file. 

```coffeescript
# app.coffee
markdown = require 'marked'

locals:
  markdown: marked
```

I've tested this in your project, and it works. since you had `marked` in your `package.json` already, I just passed that to your `markdown` local and it's accessible in all of your views.

**Comment by slang800** [comment]
If you're writing with jade, you should be able to use the `:markdown` filter, right?

```jade
:markdown
  Markdown is **much** easier to write than [HTML](http://www.w3.org/html/‎).
```

```html
<p>Markdown is <strong>much</strong> easier to write than
<a href="http://www.w3.org/html/‎">HTML</a>.</p>
```

**Comment by javaporter** [comment]
@kylemac This works like a charm, thanks man. 

Just in case others run into this later, the proper syntax once you've done as Kyle suggested is: `!= markdown(post.body)`

**Comment by joshrowley** [comment]
Awesome, glad you're all set @javaporter. Thanks for helping out @kylemac @slang800!

**Comment by EnMod** [comment]
After doing as @javaporter suggested and changing the syntax to `!= markdown(post.body)`, I get escaped characters and entities...any way to have it render valid HTML instead?

**Comment by kylemac** [comment]
@EnMod can you give us the code you're using so we can help you debug?

you may want to look into jade's interpolation docs, to begin - http://jade-lang.com/reference/interpolation/

**Comment by EnMod** [comment]
Sure thing:

```jade
extends _bloglayout

block content
	h1 Hello World
	ul
		- for post in contentful.blog_posts
			li
				h2= post.title
				!= markdown(post.body)
```

produces unescaped HTML.  Changing the markdown bit to 

```jade
:markdown
  != !{post.body}
```

produces the same results.

**Comment by javaporter** [comment]
@EnMod have you seen any oddities with lists (such as this: https://github.com/javaporter/roots-contentful-foundation/issues/6)
