### ISSUE TITLE
asset helper throws "undefined is not a function" TypeError

### ISSUE THREAD

**Issue by eholzwarth** [carrot/roots-contentful#18]
The asset helper is throwing a "undefined is not a function" TypeError for me

```javascript
for person in contentful.team_member
  img(src="#{person.profile.fields.file.url}" height='150' width='150') // this works fine
  img(src="#{asset(person.profile, {w: 150, h: 150})}" height='150' width='150') // this throws "undefined is not a function" TypeError
  img(src!= asset(person.profile, {w: 100, h: 100})) // this throws "undefined is not a function" TypeError
```

Any ideas?

**Comment by javaporter** [comment]
I'm having the same issue: 

```
img(src!= asset(post.image, {w: 100, h: 100}))
```

**Comment by joshrowley** [comment]
@eholzwarth, can you check that you're on version `0.0.7`, that's when the asset helper was added. If it's still causing an error, can you `console.log(person.profile)` and post the results here please?

**Comment by eholzwarth** [comment]
Good call - all better on 0.0.7 - sorry for the false alarm!
