### ISSUE TITLE
Get linked content

### ISSUE THREAD

**Issue by Gioni06** [carrot/roots-contentful#19]
Hi, I was wondering if there is a way to get associated content for a content type.
Lets say you have a blog post and each one has an author which is its own content type.?

**Comment by Gioni06** [comment]
i figured it out.  You just have to make another loop inside your main loop.

**Comment by mwickett** [comment]
@Gioni06 Do you have a code example you'd mind sharing? I'm really new to JS and love Roots & Contentful but am struggling with accessing nested objects (like authors properties inside of an entry) in a Jade view. I know this is like 6 months old, but I'm stumped right now!

**Comment by Gioni06** [comment]
@mwickett Sure, i'll look through some projects and share the code with you soon.

**Comment by mwickett** [comment]
@Gioni06 Thanks, I really appreciate you sharing your time.

**Comment by Rodolfocartas** [comment]
Hello @Gioni06. Could you please post the code here as well. I'm trying to access linked content but I only get the object that describes how to access it: type, id, etc. Thanks

**Comment by tkraak** [comment]
Have you guys ever shared any code? I'm very much interested in this as well. Thanks.
