### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by EnMod** [carrot/roots-contentful#20]
For some reason, when Roots gets to the `for` loop in the `jade` example in the readme, I get the title error.  

I'm using the sample code provided in the examples, as well as a slightly modified app.coffee because `slugify` was also ending up being not defined.

```jade
h1 Hello World
ul
  - for post in contentful.posts
    li
      h2= post.title
      p= markdown(post.body)
```

My `app.coffee`:

```coffee
axis         	= require 'axis'
rupture      	= require 'rupture'
typographic  	= require 'typographic'
contentful 		= require 'roots-contentful'
dynamic_content = require 'dynamic-content'
autoprefixer 	= require 'autoprefixer-stylus'
js_pipeline  	= require 'js-pipeline'
css_pipeline 	= require 'css-pipeline'
string			= require 'string'

module.exports =
	ignores: ['readme.md', 'gulpfile.js', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

	extensions: [
		js_pipeline(files: 'assets/js/*.coffee','assets/js/*.ls'),
		css_pipeline(files: 'assets/css/dev/*.styl')
		dynamic_content()
		contentful
			access_token: 'my_token'
			space_id: 'my_id'
			content_types:
				blog_posts:
					id: 'my_id'
					name: 'posts'
					template: 'views/_post.jade'
					path: (e) -> "blogging/#{e.category}/#{string(e.title).slugify().s}"
	]

	stylus:
		use: [axis(), rupture(), typographic(), autoprefixer()]
		sourcemap: true

	'coffee-script':
		sourcemap: true

	jade:
		pretty: true
```

Is it just something really rudimentary I just missed on writing these files?

**Comment by Gioni06** [comment]
I think it should be :
```Jade
h1 Hello World
ul
  - for post in contentful.blog_posts
    li
      h2= post.title
      p= markdown(post.body)
```

**Comment by EnMod** [comment]
Woww...that confused me somehow in the readme...that was probably just me though.  Thanks.  Would anyone be able to comment on why the `slugify()` part in `app.coffee` didn't work out of the box?

**Comment by kylemac** [comment]
@EnMod the `stringify` function is from the [string.js](https://www.npmjs.com/package/string) library. you need to ensure it's in your `package.json` as a dependency and make sure that `string(e.title).slugify().s` is valid per their documentation. 

for what it's worth - we've moved from using string.js to using [underscore.string](http://epeli.github.io/underscore.string/) for this type of operation. it's comparable function would be `string.slugify(e.title)`.

**Comment by EnMod** [comment]
It seems installing underscore.string and adding `slugify = require 'underscore.string/slugify'` to `app.coffee`, then using the out of the box syntax produced no errors. Thanks so much!

**Comment by kylemac** [comment]
great! let us know if you come across any other issues along the way
