### ISSUE TITLE
Sample code for a single entry view?

### ISSUE THREAD

**Issue by EnMod** [carrot/roots-contentful#21]
From what I gather, `contentful.some_content_type` returns an array containing all entries in said content type.  How would I structure the Jade in my single entry view to only grab one entry (say, one blog post) per generation of single entry view though? Currently my template produces (obviously) output containing all posts.

```jade
extends _bloglayout

block content
	each post in contentful.blog_posts
		h1= post.title
		!= markdown(post.body)
```
I'm kind of unsure how else I'd structure it so Roots can iterate through the array on each view generation.  I get the feeling there's something very fundamental I'm missing regarding how roots-contentful does its generation of single entry views.

**Comment by Gioni06** [comment]
content_types:
        blog_posts:
          id: '1fUnrMgZL8WeSu26AYQyOY'
          template: 'views/_single.jade'
          path: (e) -> "blog/#{slugify(e.title)}"

This will render each blog post to into a HTML file in /blog/My-post.HTML

In your template you do not need to loop through post, but you need to know that each post gets resolved as 'entry'  exp. entry.title

**Comment by EnMod** [comment]
Using `entry` for my entry data is exactly what I was looking for, chalk that one up to common sense lol.  Thanks for the reply! Closing
