### ISSUE TITLE
strange issues with markdown

### ISSUE THREAD

**Issue by javaporter** [carrot/roots-contentful#22]
In the first screenshot, the markdown from contentful is coming in quite strange. There's an `<li>` for the first item, then `<li><p>`, the ol is completely borked as well. The same exact contentful markdown works fine through middleman_contentful (see other screenshot). 

```jade
- for post in contentful.snuggle
          article.test
            date= post.date
            h1= post.title
            if post.heroImage
              img(src=asset(post.heroImage, {w: 1100, h: 1100}))
            != markdown(post.body)
```
![screenshot 2015-04-27 08 27 56](https://cloud.githubusercontent.com/assets/170182/7349586/72560926-ecb7-11e4-8225-62ab61c7a170.png)

![screenshot 2015-04-27 08 30 59](https://cloud.githubusercontent.com/assets/170182/7349630/c6343748-ecb7-11e4-96c5-4529ae7664ae.png)

**Comment by jenius** [comment]
Man, I have no idea. Is it potentially the markdown function you're running it through? Does `post.body` output the correct markdown? What exactly is that `markdown` function?

**Comment by javaporter** [comment]
I started using that based on this: https://github.com/carrot/roots-contentful/issues/13

`post.body` does output the correct markdown

**Comment by jenius** [comment]
Seems like a marked issue then, right? Not sure I can do much to fix this...

**Comment by slang800** [comment]
ref: https://github.com/chjj/marked/issues/55

**Comment by javaporter** [comment]
yep, looks like an issue with marked, I'll address it there, thanks
