### ISSUE TITLE
roots-contentful doesn't play well with roots-yaml

### ISSUE THREAD

**Issue by axelboc** [carrot/roots-contentful#31]
I'm trying to use **roots-contentful** in combination with **[roots-yaml](https://github.com/carrot/roots-yaml)**. Basically I need to access the `data` object created by roots-yaml from inside the single entry views compiled by roots-contentful. Unfortunately, the `data` object is `undefined` when I try to reference it from my views.

The problem seems to be that the views are compiled during the set-up of roots-contentful (inside the `setup` hook), but the `data` object is created by roots-yaml much later, in the `before_pass` compile hook.

The `ordered` flag has no effect, of course, since the extension is not dealing with files like roots-yaml is. If roots extensions had some sort of `cleanup` hook, the compilation could be moved in there, but there isn't.

The only solution I could find is to make the `compile_entries` function available on the Roots object, and to call it from the `after` hook in my project's `app.coffee`.

`root-contentful/lib/index.coffee`

``` coffee
# ...

    setup: ->
      types = opts.content_types
      types = if _.isPlainObject(types) then reconfigure_alt_type_config(types)
      @roots.compileContentfulViews = compile_entries.bind(@, types)

      configure_content(types).with(@)
        .then(get_all_content)
        .tap(set_urls)
        .tap(set_locals)

# ...
```

`app.coffee`

``` coffee
# ...

    after: (roots) ->
      roots.compileContentfulViews()

# ...
```

**Comment by signorekai** [comment]
+1 for issue.
