### ISSUE TITLE
Potentially unhandled rejection

### ISSUE THREAD

**Issue by branquito** [carrot/roots-contentful#66]
`The query you sent was invalid. Probably a fiter or ordering specification is not applicable to the type of a field.`

I am getting this error when trying to fetch data from contentful into roots.. followed your tutorial.

Thx.

**Comment by declandewet** [comment]
Hi @branquito. As per this note on our [contribution guidelines](https://github.com/carrot/roots-contentful/blob/master/contributing.md)

> ### Filing Issues
> 
> If you are opening an issue about a bug, make sure that you include clear steps for how we can reproduce the problem. If we can't reproduce it, we can't fix it.

We'll need a little more information to help you debug your issue. At the very least, it would be helpful if you could include the following in your bug report:

1. Your version of Node.js (`node -v`)
2. Your version of NPM (`npm -v`)
3. Your version of `roots` (`roots -v`)
4. Your version of `roots-contentful` (found in your project's `package.json`)
5. If there is a clear error message on the console, then the entire error stack trace or a copy of the `npm-debug.log` file after this error has occurred.
6. A copy of your `app.coffee` (be sure to redact any sensitive information like API tokens before sharing!)

**Comment by branquito** [comment]
sorry, my bad.. the problem was I din't specify `id` of a correct entity.. because it was hard to find that information as it is now in a completely unlogical section of Contentful site.. later when I finally found it and exchanged it for previously entered(which was for one specific post, and therefore an error) everything worked fine. thanks.

**Comment by dhaabi** [comment]
@branquito, where did you manage to find it?  i haven't been able to get the id and have been getting the same issue

**Comment by epcrowley** [comment]
@dhaabi I had the same issue when following the tutorial. I had used the wrong id. I had taken the id from a blog entry I had created, but instead you need to go into "Content model explorer" in the API section, and copy the identifier (in my case for blog) from there. Worked after that.
