### ISSUE TITLE
Client side template integration

### ISSUE THREAD

**Issue by sethkrasnianski** [carrot/roots-contentful#8]
Is there a way to output the Contentful space template to the client `template.js`?

**Comment by jenius** [comment]
Are you talking about sending it to the roots-client-templates extension? If so, there is not a method right now for exchanging information between different extensions, this is extraordinarily complicated.

**Comment by joshrowley** [comment]
You can have your Contentful template in whatever folder is holding your client side templates for roots-client-templates and then point roots-contentful to the same file.

**Comment by jenius** [comment]
Good call! Let us know if this worked @sethkrasnianski

**Comment by joshrowley** [comment]
Closing this issue out, let us know if this worked out for you @sethkrasnianski

**Comment by sethkrasnianski** [comment]
Late response, haven't tried it. Task was pushed to the bottom of the list. But I will try this... sounds promising. :+1: thanks

**Comment by Fprince333** [comment]
I'm trying to do the exact same thing - tried this a few different ways but can't seem to get it. Opened an issue [here](https://github.com/carrot/roots-client-templates/issues/24) but I think this thread is what i'm looking for. Anyone get this to work?

**Comment by javiercf** [comment]
@joshrowley Didn't seem to work, if someone has made any progress with this would really like to know about it

**Comment by joshrowley** [comment]
@javiercf Hey, I haven't used roots in a while, and unfortunately don't have the bandwidth to help anybody with this, but I'm sure you can find some help in the gitter chatroom for roots! :smile: https://gitter.im/jenius/roots
